<?php 

require_once BASEPATH.'autoload.php';

echo userHTML( );

$symbApprove = '<i class="fa fa-thumbs-o-up fa-2x"></i>';
$symbReject = '<i class="fa fa-thumbs-o-down fa-2x"></i>';

?>

<script type="text/javascript">
function toggleMe(source) {
    var checkboxes = document.getElementsByName( 'events[]' );
    for( var index = 0; index < checkboxes.length; ++index )
        checkboxes[index].checked = source.checked;
}
</script>


<?php
if( ! array_key_exists( 'response', $_POST ) )
{
    flashMessage( "Nothing to do here." );
    redirect( 'adminbmv/home' );
}

if( $_POST['response'] == "Review" )
{
    echo '<div>';
    // Approve after constructing all the events from the patterns.
    $requests = getRequestByGroupIdAndStatus( $_POST['gid'], 'PENDING' );
    $gid = $requests[0]['gid'];
    $total = count( $requests );

    echo "<h2> Following events are generated by this request </h2>";

    // First insert this request into event calendar.
    echo '<div style="font-size:small">';
    echo '<form method="post" action="'.site_url('adminbmv/request_review').'">';
    echo '<table class="show_events">';
    $childrenId = 0;

    $jcLabmeets = getLabmeetAndJC( );

    $collideWith = array( );
    foreach( $requests as $r )
    {
        $rid = $r['rid'];
        // use this id to get back the gid and rid in next form. 
        $id = $gid . '.' . $rid;
        echo "<tr>";
        echo "<td><input type=\"checkbox\" name=\"events[]\" value=\"$id\" checked></td>";
        $hide = 'rid,description,status,created_on,is_public_event'
            . ',calendar_id,calendar_event_id,url,last_modified_on,'
            . 'external_id,modified_by';

        echo "<td>" . arrayToTableHTML( $r, 'request', '', $hide ) . "</td>";

        $date = $r['date'];
        $stime = $r[ 'start_time'];
        $etime = $r[ 'end_time'];
        $venue = $r[ 'venue' ];

        $jcOrLab = clashesOnThisVenueSlot( $date, $stime, $etime, $venue, $jcLabmeets );

        if( $jcOrLab )
        {
            echo "<td>See warning below</td>";
            $collideWith[ ] = $jcOrLab;
        }
        else
            echo "<td>Clean</td>";

    }

    $yesChecked = '';
    $noChecked = '';
    if( $requests[0][ 'is_public_event' ] == 'YES' )
        $yesChecked = 'checked';
    else
        $noChecked = 'checked';

    echo '</td>';
    echo "</tr> </table>";

    echo "<input name=\"request[]\" type=\"checkbox\" checked
        onclick=\"toggleMe(this)\" />Select all</td>
        ";

    $collisedWithText = array( );
    if( count( $collideWith ) > 0 )
    {
        echo '<h2>Warning</h2>';
        echo alertUser( "Warning: User is trying to book venue/slot where following 
            JCs or LABMEETs usually booked. Please be extra careful while approving!" 
        );
        foreach( $collideWith as $entries )
            foreach( $entries as $entry )
                $collisedWithText[ $entry[ 'title' ] ] = $entry;

        $collisionEvents = array_values( $collisedWithText );
        $table = '<table class="info">';
        $table .= arrayHeaderRow( $collisionEvents[0], '', $hide );

        foreach( $collisionEvents as  $event )
            $table .= arrayToRowHTML( $event, '', $hide );

        $table .=  '</table>';
        echo $table;
    }

    echo "<br />";
    echo '</div>';

    echo '<table style="border:1px;position:"relative";"> ';

    echo "<tr> 
            <!-- Here we create the button to submit requests -->
            <td> Suitable for public google-calendar 
                <input name=\"isPublic\" value=\"YES\" type=\"radio\" $yesChecked />Yes
                <input name=\"isPublic\" value=\"NO\" type=\"radio\" $noChecked />No
                </td>
            </tr>
            <tr>
                <td> </td>
                <td>
                    <button name=\"response\" value=\"APPROVE\" 
                        title=\"Approve selected\">" . $symbApprove . "</button>
                </td>
            </tr>
            <tr> 
                <td>
                Reason for rejection <br />
                <textarea rows=\"4\" cols=\"50\" name=\"reason\" 
                    placeholder=\"Mandatorty while rejecting a request \"
                    ></textarea>
                </td>
                <td>
                    <button name=\"response\" value=\"REJECT\"
                        title=\"Reject selected\">" . $symbReject . "</button>
                </td>
            </tr>
            <input type=\"hidden\" name=\"gid\" value=\"$gid\" /> 
        </table>
        ";
    echo "</form>";
    echo '</div>';
}

echo goBackToPageLink( "adminbmv/home", "Go back" );

?>
