#!/bin/bash
set -e

export http_proxy=http://proxy.ncbs.res.in:3128/
export https_proxy=http://proxy.ncbs.res.in:3128/

# ( cd /var/www/html/hippo && /usr/bin/git pull && ls -ltra )

# Apache gets grumpy about PID files pre-existing
# rm -f /usr/local/apache2/logs/httpd.pid

a2enmod php7
exec apache2ctl -DFOREGROUND "$@"
